POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hdGhhbnRlc3RAZW1haWwuY29tIiwiZXhwIjoxNzA4NjI2NjcyLCJ1c2VySWQiOjB9.NrF3HfKry2U92WvLAl2NPPGnLZL_OPpdgSduGO7OFu8

{
    "name":"Nathan Teste 2",
    "description" : "Teste teste",
    "location": "test location",
    "datetime": "2024-01-01T15:39:00.000Z"
}