DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiZXhwIjoxNzA4NjI5NjAzLCJ1c2VySWQiOjJ9.KozRSbI3OdG8lB4_67BxfWmeBegNu7-Gm5vi8AUPscc