DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiZXhwIjoxNzA4NjI4ODE2LCJ1c2VySWQiOjJ9.YXhiccY9ndNwEgyl9F_kLk6dCNXWddWUwOfs_JsHy68