PUT http://localhost:8080/events/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiZXhwIjoxNzA4NjI5MzUzLCJ1c2VySWQiOjJ9.8udHXmlWjcmX4GvKtHKPN5fip2e8ZzFBYI3SB7BSHc8

{
    "ID": 4,
    "Name": "Updated Teste",
    "Description": "Updated teste",
    "Location": "test location",
    "DateTime": "2024-01-01T15:39:00Z",
    "UserId": 1
  }